cats99/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :cats, except: [:destroy]

  # Defines the root path route ("/")
  root "cats#index"
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  CAT_COLOR = ['gray', 'black', 'white', 'blue', 'purple', 'brown']

  validates :birth_date, :color, :name, :sex, presence: true
  validate :birth_date_cannot_be_future, :valid_cat_color, :valid_sex

  def birth_date_cannot_be_future
    if birth_date > Date.today
      errors.add("Birthday can't be in the future")
    end
  end

  def valid_cat_color
    if !CAT_COLOR.include?(color)
      errors.add("Invalid color")
    end
  end

  def valid_sex
    if !['M', 'F'].include?(sex)
      errors.add("Invalid sex")
    end
  end

  def age
    # ((Date.today - birth_date)/365.0).round
    time_ago_in_words(birth_date)
  end
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat.id)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat.id)
    else
      render :edit
      # redirect_to "https://httpstatusdogs.com/img/422.jpg", allow_other_host: true
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cats/_form.html.erb
<%# action_url = (action == :create ? cats_url : cat_url(cat.id) ) %>
<%# submit_text = (action == :create ? "Create Cat" : "Update Cat") %>

<% action_url = (cat.persisted? ? cat_url(cat.id) : cats_url) %>
<% submit_text = (cat.persisted? ? "Update Cat" : "Create Cat") %>

<form action="<%= action_url %>" method="POST">
  <%# if action == :update %>
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <legend>Sex</legend>
  <input id="male" type="radio" name="cat[sex]" value="M" <%= "checked" if cat.sex == "M" %>>
  <label for="male">Male</label>
  <input id="female" type="radio" name="cat[sex]" value="F" <%= "checked" if cat.sex == "F" %>>
  <label for="female">Female</label>
  
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <%# if action == :create %>
    <% if !cat.persisted? %>
      <option disabled selected value="">Select a color</option>
    <% end %>
    
    <% Cat::CAT_COLOR.each do |color| %>
      <option value="<%= color %>" <%= "selected" if cat.color == color %>><%= color %></option>
    <% end %>
  </select>
  
  <br>

  <label for="birth_date">Birthday</label>
  <input id="birth_date" type="date" max="<%= Time.now.strftime("%Y-%m-%d") %>" name="cat[birth_date]" value="<%= cat.birth_date %>">
  
  <br>

  <label for="description">Description</label>
  <input id="description" type="textarea" name="cat[description]" value="<%= cat.description %>">

  <br>

  <input type="submit" value="<%= submit_text %>">
</form>

cats99/app/views/cats/edit.html.erb
<h1>Edit Info</h1>

<%= render 'form', cat: @cat, action: :update %>

cats99/app/views/cats/index.html.erb
<h1>These are my cats</h1>

<ol>
<% @cats.each do |cat| %>
  <a href=<%= cat_url(cat.id) %>>
    <li><%= cat.name %></li>
  </a>
<% end %>
</ol>

<a href="<%= new_cat_url %>">Add New Cat</a>

cats99/app/views/cats/new.html.erb
<h1>Make a new kitty :3</h1>

<%= render "form", cat: @cat, action: :create %>

cats99/app/views/cats/show.html.erb
<table>
  <thead>
    <tr>
      <th colspan="2">
        <%= @cat.name %>'s Info
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>ID</td>
      <td><%= @cat.id %></td>
    </tr>
    <tr>
      <td>Birthday</td>
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color</td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>Sex</td>
      <td><%= @cat.sex == 'M' ? "Male" : "Female" %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<a href="<%= edit_cat_url(@cat.id) %>">Edit</a>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>